name: duplo deployment

on:
  workflow_call:
    inputs:
      target_s3_bucket:
        required: true
        type: string
      cloudfront_distribution_id:
        required: true
        type: string
      duplo_tenant:
        required: true
        type: string
      api_url:
        required: true
        type: string
      app_url:
        required: true
        type: string
      aws_region:
        type: string
        default: us-east-1
      react_app_stage:
        required: true
        type: string
    secrets:
      duplo_host:
        required: true
      duplo_token:
        required: true

jobs:
  deploy-to-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: AWS just-in-time access
        uses: duplocloud/ghactions-aws-jit@master
        with:
          duplo_host: ${{ secrets.duplo_host }}
          duplo_token: ${{ secrets.duplo_token }}
          tenant: ${{ inputs.duplo_tenant }}

      - name: Sync files to S3
        run: |-
          ls build/*
          # Sync files to S3 from a local directory named "build"
          #aws s3 sync build/ "s3://${{ inputs.target_s3_bucket }}/"
          aws s3 sync build/ "s3://${{ inputs.target_s3_bucket }}/${{ github.sha }}"

      - name: CF update the origin path based on github sha
        run: |-
          new_origin_path=/${{ github.sha }}
          cloudfront_origin_id=duploservices-raghavan01-s3app1-386269687991.s3.us-east-1.amazonaws.com  # CHANGE ME
          temp_distconfig_old="distconfig-old.json"
          temp_distconfig_new="distconfig-new.json"
          aws cloudfront get-distribution --id ${{inputs.cloudfront_distribution_id}} > $temp_distconfig_old
          Etag=`cat $temp_distconfig_old | jq '.ETag' | tr -d \"`
          cat $temp_distconfig_old | jq --arg targetOriginId $cloudfront_origin_id --arg newOriginPath $new_origin_path '.Distribution.DistributionConfig | .Origins.Items = (.Origins.Items | map(if (.Id == $targetOriginId) then (.OriginPath = $newOriginPath) else . end))' > $temp_distconfig_new
          cat $temp_distconfig_new
          aws cloudfront update-distribution --id ${{inputs.cloudfront_distribution_id}} --distribution-config "file://${temp_distconfig_new}" --if-match $Etag > /dev/null
          rm -f $temp_distconfig_old $temp_distconfig_new

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: '${{ inputs.cloudfront_distribution_id }}'
          PATHS: '/*'
