name: duplo deployment

on:
  workflow_call:
    inputs:
      target_s3_bucket:
        required: true
        type: string
      cloudfront_distribution_id:
        required: true
        type: string
      duplo_tenant:
        required: true
        type: string
      api_url:
        required: true
        type: string
      app_url:
        required: true
        type: string
      aws_region:
        type: string
        default: us-east-1
      react_app_stage:
        required: true
        type: string
    secrets:
      duplo_host:
        required: true
      duplo_token:
        required: true

jobs:
  deploy-to-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: AWS just-in-time access
        uses: duplocloud/ghactions-aws-jit@master
        with:
          duplo_host: ${{ secrets.duplo_host }}
          duplo_token: ${{ secrets.duplo_token }}
          tenant: ${{ inputs.duplo_tenant }}

      - name: Sync files to S3
        run: |-
          ls build/*
          # Sync files to S3 from a local directory named "build"
          aws s3 sync build/ "s3://${{ inputs.target_s3_bucket }}/"
          aws s3 sync build/ "s3://${{ inputs.target_s3_bucket }}/${{ github.sha }}"

      - name: CF update
        run: |-
          NEW_ORIGIN_PATH="{{ github.sha }}"
          CLOUDFRONT_ORIGIN_ID="E1QGIWKA2DZY0A"
          DIST_CONFIG_OLD_FILENAME="dist-config.json"
          DIST_CONFIG_NEW_FILENAME="dist-config2.json"
          aws cloudfront get-distribution --id ${{inputs.cloudfront_distribution_id}} > $DIST_CONFIG_OLD_FILENAME
          Etag=`cat $DIST_CONFIG_OLD_FILENAME | jq '.ETag' | tr -d \"`
          echo $Etag
          cat $DIST_CONFIG_OLD_FILENAME | jq --arg targetOriginId $CLOUDFRONT_ORIGIN_ID --arg newOriginPath $NEW_ORIGIN_PATH '.Distribution.DistributionConfig | .Origins.Items = (.Origins.Items | map(if (.Id == $targetOriginId) then (.OriginPath = $newOriginPath) else . end))' > $DIST_CONFIG_NEW_FILENAME
          cat $DIST_CONFIG_NEW_FILENAME
          rm -f $DIST_CONFIG_OLD_FILENAME $DIST_CONFIG_NEW_FILENAME

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: '${{ inputs.cloudfront_distribution_id }}'
          PATHS: '/*'
