name: duplo revert

on:
  workflow_dispatch:
    inputs:
      cloudfront_distribution_id:
        required: true
        type: string
        default: E1QGIWKA2DZY0A
      duplo_tenant:
        required: true
        type: string
        default: raghavan01
      api_url:
        required: true
        type: string
        default: https://api_url
      app_url:
        required: true
        type: string
        default: https://app_url
      aws_region:
        type: string
        default: us-east-1
      git_hub_sha:
        required: true

env:
  duplo_host: https://test01.duplocloud.net  # CHANGE ME!

jobs:
  revert-to-previous:
    name: Deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: AWS just-in-time access
        uses: duplocloud/ghactions-aws-jit@master
        with:
          duplo_host: ${{ env.duplo_host }}
          duplo_token: "${{ secrets.DUPLO_TOKEN }}"
          tenant: ${{ inputs.duplo_tenant }}

      - name: CF revert
        run: |-
          NEW_ORIGIN_PATH=/${{ inputs.git_hub_sha }}
          CLOUDFRONT_ORIGIN_ID="duploservices-raghavan01-s3app1-386269687991.s3.us-east-1.amazonaws.com"
          DIST_CONFIG_OLD_FILENAME="dist-config.json"
          DIST_CONFIG_NEW_FILENAME="dist-config2.json"
          aws cloudfront get-distribution --id ${{inputs.cloudfront_distribution_id}} > $DIST_CONFIG_OLD_FILENAME
          Etag=`cat $DIST_CONFIG_OLD_FILENAME | jq '.ETag' | tr -d \"`
          cat $DIST_CONFIG_OLD_FILENAME | jq --arg targetOriginId $CLOUDFRONT_ORIGIN_ID --arg newOriginPath $NEW_ORIGIN_PATH '.Distribution.DistributionConfig | .Origins.Items = (.Origins.Items | map(if (.Id == $targetOriginId) then (.OriginPath = $newOriginPath) else . end))' > $DIST_CONFIG_NEW_FILENAME
          cat $DIST_CONFIG_NEW_FILENAME
          aws cloudfront update-distribution --id ${{inputs.cloudfront_distribution_id}} --distribution-config "file://${DIST_CONFIG_NEW_FILENAME}" --if-match $Etag > /dev/null
          rm -f $DIST_CONFIG_OLD_FILENAME $DIST_CONFIG_NEW_FILENAME

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: '${{ inputs.cloudfront_distribution_id }}'
          PATHS: '/*'
