# This is a basic workflow to help you get started with Actions
name: CI-CD-Revert

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  duplo_host: https://test01.duplocloud.net  # CHANGE ME!
  duplo_token: "${{ secrets.DUPLO_TOKEN }}"
  SERVICE_NAME: mynodejs                      # CHANGE ME!
  TENANT_NAME: raghavan01                       # CHANGE ME!
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copys3:
    name: Deploy to dev
    uses: ./.github/workflows/duplo_revert.yml
    with:
      api_url: https://api_url
      app_url: https://app_url
      duplo_tenant: raghavan01
      react_app_stage: development
      cloudfront_distribution_id: E1QGIWKA2DZY0A
      target_s3_bucket: duploservices-raghavan01-s3app1-386269687991
    secrets:
      duplo_host: https://test01.duplocloud.net
      duplo_token: ${{ secrets.DUPLO_TOKEN }}
